# Generated by Django 3.1 on 2020-08-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0004_target_voters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='target',
            old_name='content',
            new_name='target',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='target',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='target',
            name='small_target_1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='target',
            name='small_target_2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='target',
            name='small_target_3',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='target',
            name='target_reason',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='target',
            name='target_term',
            field=models.CharField(default='', max_length=50),
        ),
    ]
