# Generated by Django 3.1 on 2020-08-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0005_auto_20200812_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='small_target_1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='target',
            name='small_target_2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='target',
            name='small_target_3',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='target',
            name='target_reason',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='target',
            name='target_term',
            field=models.CharField(max_length=50),
        ),
    ]
