# Generated by Django 3.1 on 2020-08-18 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0006_auto_20200813_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='target_image',
            field=models.ImageField(height_field=models.IntegerField(editable=False), null=True, upload_to='files/', verbose_name='添付画像', width_field=models.IntegerField(editable=False)),
        ),
        migrations.AlterField(
            model_name='target',
            name='small_target_1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='target',
            name='small_target_2',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='target',
            name='small_target_3',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='target',
            name='target',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='target',
            name='target_reason',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='target',
            name='target_term',
            field=models.CharField(max_length=20),
        ),
    ]
