# Generated by Django 3.1 on 2020-08-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0007_auto_20200818_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='target_image',
            field=models.ImageField(null=True, upload_to='media/', verbose_name='添付画像'),
        ),
    ]
