# Generated by Django 3.1 on 2020-08-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0008_auto_20200818_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='target_image',
            field=models.ImageField(null=True, upload_to='files/', verbose_name='添付画像'),
        ),
    ]
