# Generated by Django 3.1 on 2020-08-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0009_auto_20200818_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='target_image',
            field=models.ImageField(blank=True, null=True, upload_to='files/', verbose_name='添付画像'),
        ),
    ]
