# Generated by Django 3.1 on 2020-08-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0010_auto_20200818_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='target_image',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
