# Generated by Django 3.1 on 2020-08-23 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0012_auto_20200822_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='target_image',
        ),
        migrations.AddField(
            model_name='target',
            name='done_comment',
            field=models.TextField(null=True),
        ),
    ]
